apiVersion: v1
kind: Service
metadata:
  name: webpage-active
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: Service
metadata:
  name: webpage-preview
spec:
  selector:
    app: webpage
  ports:
  - port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: webpage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webpage
  template:
    metadata:
      labels:
        app: webpage
    spec:
      containers:
      - name: webpage
        image: fabricioveronez/pagina-exemplo:green
        ports:
        - containerPort: 80
  strategy:
    blueGreen:
      activeService: webpage-active
      previewService: webpage-preview
      autoPromotionEnabled: false
      autoPromotionSeconds: 30
